services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    env_file:
      - ./Database/.env
    networks:
      - internal_network
    stop_grace_period: 30s

  webscraper:
    build:
      context: './WebScraper'
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '3000:3000'
    env_file:
      - ./WebScraper/.env
    networks:
      - internal_network
networks:
  internal_network:
